{%include file="header.phtml"%}

<body id="admin">
    <div id="top">
	<h1>OpenSocial APP Control Panel</h1>
	</div>
	<div id="container">
		<div id="auth">
			<p>システムからログアウトしました。再度ログインするには「ログイン画面へ」ボタンを押して下さい。</p><br />
			<center><input type="button" value="　ログイン画面へ　" onclick="window.location.href='{%$baseUrl%}/';" /></center>
		</div><!--/#auth-->
	</div><!--/#container-->

{%include file="footer.phtml"%}