{%include file="user/commonmenu.phtml"%}

	<div id="container">
		<h2>管理ユーザー削除</h2>
		<div id="admin">
		    <p><a href="{%$baseUrl%}/user/managertop">管理ユーザー一覧</a>　&gt;&gt;管理ユーザー削除</p>
		    <p>
			登録済み管理ユーザー [ID:{%$managerInfo.uid%}　{%$managerInfo.name|escape%}] の削除します。削除しますと、付随するデータも削除されます。この情報を削除するには管理パスワードの入力が必要です。よろしければ、管理パスワードを入力し「削除」ボタンを押して下さい。
			</p>
			<div id="completeMsg" style="display:none" class="completeMsg"></div>
			<table width="100%"　style="clear: both;" class="mytable">
    			<tr><th style="width:220px;table-layout:fixed;">設定項目</th><th>設定内容</th></tr>
    			<tr><td>ユーザー名：<br/>（ログインID）</td><td>{%$managerInfo.login_id|escape%}</td>
    			</tr>
                <tr><td>パスワード</td><td>******</td>
                </tr>
                <tr><td>管理パスワード入力：</td><td><input type="password" id="txtPW" name="txtPW" onblur="jQuery.deluser.checkPWValue()" maxlength="50" size="60" />
                <div class="validation-advice" id="divPWErr" title="パスワードを入力して下さい。" style="display:none;"></div></td></tr>
                <tr><td colspan="2"><input type="button" id="btnDelete" value="削除" /></td>
			</table>
            <input type="hidden" id="hidUid" name="hidUid" value="{%$managerInfo.uid%}" />
            <input type="hidden" id="hidType" name="hidType" value="2" />
<br />
			<form method="post" id="frmBack" >
    			<input type="hidden" id="pageIndex" name="pageIndex" value="{%$pageIndex%}" />
                <input type="hidden" id="hidSrhName" name="hidSrhName" value="{%$hidSrhName%}" />
                <input type="hidden" id="hidSrhOwner" name="hidSrhOwner" value="{%$hidSrhOwner%}" />
                <input type="hidden" id="hidSrhCate" name="hidSrhCate" value="{%$hidSrhCate%}" />
    			<a href="javascript:void(0);" id="btnBack">&lt;&lt;前の画面へ</a>
			</form>
		</div><!--/#auth-->
	</div><!--/#container-->
	<script src="{%$staticUrl%}/admin/js/user/deluser.js?{%$version.js%}"></script>

{%include file="footer.phtml"%}