{%include file="user/commonmenu.phtml"%}

	<div id="container">
		<h2>アプリケーションオーナー詳細</h2>
		<div id="admin">
		    <p><a href="{%$baseUrl%}/user/ownertop">アプリケーションオーナー一覧　</a>　&gt;&gt;アプリケーションオーナー詳細</p>
		    <p>登録済みアプリケーションオーナー [ID:{%$ownerInfo.uid%}　{%$ownerInfo.name|escape%}] の詳細情報を表示しています。登録アプリ一覧の各種管理エリアから任意の管理画面へ遷移できます。オーナーの管理画面へのアクセスログは「アクセスログ」ボタンを押すと表示されます。</p>
			<div id="completeMsg" style="display:none" class="completeMsg"></div>
			<table width="100%"　style="clear: both;" class="mytable">
    			<tr><th style="width:220px;table-layout:fixed;">設定項目</th><th>設定内容</th></tr>
    			<tr class="overlight"><td>オーナー名（会社名）：※</td><td>{%$ownerInfo.name|escape%}</td>
    			</tr>
    			<tr><td>管理サイトログインID：※</td><td>{%$ownerInfo.login_id|escape%}</td>
    			</tr>
    			<tr class="overlight"><td>登録アプリサイト数：※</td><td>{%$ownerInfo.app_count%}</td>
    			</tr>
    			<tr><td>管理サイトサイト名：※</td><td>{%$ownerInfo.apps|escape%}</td></tr>
                <tr class="overlight"><td>管理パスワード入力：</td><td><input type="password" id="txtPW" name="txtPW" onblur="jQuery.deluser.checkPWValue()" maxlength="50" size="60" />
                <div class="validation-advice" id="divPWErr" title="パスワードを入力して下さい。" style="display:none;"></div></td></tr>
                <tr><td colspan="2"><input type="button" id="btnDelete" value="削除" /></td>
			</table>
            <input type="hidden" id="hidUid" name="hidUid" value="{%$ownerInfo.uid%}" />
            <input type="hidden" id="hidType" name="hidType" value="3" />
<br />
			<form method="post" id="frmBack" >
    			<input type="hidden" id="pageIndex" name="pageIndex" value="{%$pageIndex%}" />
                <input type="hidden" id="hidSrhName" name="hidSrhName" value="{%$hidSrhName%}" />
                <input type="hidden" id="hidSrhOwner" name="hidSrhOwner" value="{%$hidSrhOwner%}" />
                <input type="hidden" id="hidSrhCate" name="hidSrhCate" value="{%$hidSrhCate%}" />
    			<a href="javascript:void(0);" id="btnBack">&lt;&lt;前の画面へ</a>
			</form>
		</div><!--/#auth-->
	</div><!--/#container-->
	<script src="{%$staticUrl%}/admin/js/user/deluser.js?{%$version.js%}"></script>

{%include file="footer.phtml"%}