{%include file="manage/commonmenu.phtml"%}

	<div id="container">
		<h2>アプリサイト詳細</h2>
		<div id="auth">
		    <p><a href="{%$baseUrl%}/manage/listsite">管理アプリサイト一覧</a>　&gt;&gt;アプリサイト詳細</p>
		    <p>[ID:{%$siteInfo.app_id%}　{%$siteInfo.app_name|escape%}]の詳細情報を表示しています 。</p>
		    <div id="completeMsg" style="display:none" class="completeMsg"></div>
			<form method="post" id="frmDel">
    			<table width="100%" class="mytable">
    			<tr><th style="width:220px;table-layout:fixed;">設定項目</th><th>設定内容</th></tr>
    			<tr class="overlight"><td>アプリケーションID：※</td><td>{%$siteInfo.app_id%}</td></tr>
    			<tr><td>アプリケーション名：※</td><td>{%$siteInfo.app_name|escape%}</td>
    			</tr>
                <tr class="overlight"><td>ミクシィID：※</td><td>{%$siteInfo.mixi_app_id%}</td>
                </tr>
    			<tr><td>オーナー：※</td><td>{%$siteInfo.login_id|escape%}</td>
    			</tr>
    			<tr  class="overlight"><td>OpenSocialサイトURL：※</td><td>{%$siteInfo.site_url%}</td>
    			</tr>
    			<tr><td>カテゴリ：</td><td>{%$siteInfo.category_name|escape%}</td></tr>
            	<tr  class="overlight"><td>管理ツール設定：</td>
            	<td>{% if $siteInfo.log_tool %}ログ解析、{%/if%}
                    {% if $siteInfo.CGM_tool %}CGM監視、{%/if%}
                    {% if $siteInfo.point_tool %}ポイント管理、{%/if%}
                    {% if $siteInfo.affiliate_tool %}アフィリエイト、{%/if%}
                    {% if $siteInfo.adviser_tool %}アド、{%/if%}
                    {% if !$siteInfo.log_tool && !$siteInfo.CGM_tool && !$siteInfo.point_tool && !$siteInfo.affiliate_tool && !$adviser_tool.log_tool %}-{%/if%}</td></tr>
    			<tr><td>管理パスワード入力：</td><td><input type="password" id="txtPW" name="txtPW" onblur="jQuery.delapp.checkPWValue()" maxlength="50" size="60" />
    			<div class="validation-advice" id="divPWErr" title="パスワードを入力して下さい。" style="display:none;"></div></td></tr>
    			<tr><td colspan="2"><input type="button" id="btnSubmit" value="削除" /></td>
    			</table>
    			<input type="hidden" id="hidAid" name="hidAid" value="{%$siteInfo.app_id%}" />
			</form>
<br />
			<form method="post" id="frmBack" action="{%$baseUrl%}/manage/listsite">
    			<input type="hidden" id="pageIndex" name="pageIndex" value="{%$pageIndex%}" />
                <input type="hidden" id="hidSrhName" name="hidSrhName" value="{%$hidSrhName%}" />
                <input type="hidden" id="hidSrhOwner" name="hidSrhOwner" value="{%$hidSrhOwner%}" />
                <input type="hidden" id="hidSrhCate" name="hidSrhCate" value="{%$hidSrhCate%}" />
    			<a href="javascript:void(0);" id = "btnBack" >&lt;&lt;前の画面へ</a>
			</form>
		</div><!--/#auth-->
	</div><!--/#container-->
	<script src="{%$staticUrl%}/admin/js/manage/delapp.js?{%$version.js%}"></script>

{%include file="footer.phtml"%}