{%include file="manage/commonmenu.phtml"%}

	<div id="container">
		<h2>アプリケーション一覧</h2>
		<table class="search">
		<tr>
		<td nowrap>アプリケーション名：<input type="text" id="txtSrhName" name="txtSrhName" value="{%$hidSrhName%}"  maxlength="50" /></td>
		<td nowrap>オーナー：<input type="text" id="txtSrhOwner" name="txtSrhOwner" value="{%$hidSrhOwner%}"  maxlength="50" /></td>
		<td nowrap>カテゴリー：<select id="selSrhCate" name="selSrhCate">
					<option value="">選択なし</option>
					{% foreach from=$lstCate item=cateData %}
					<option value="{%$cateData.cid%}" {% if $cateData.cid==$hidSrhCate %}selected="selected"{% /if %}>{%$cateData.category_name|escape%}</option>
					{% /foreach %}
				</select></td>
		<td nowrap><input type="button" id="btnSearch" name="btnSearch" value="　検索　" />
		<input type="button" id="btnClear" name="btnClear" value="　クリア　" />
		</td>
		</tr>
	    </table>

		<p class="sub">設定済みクロール対象サイトは<span id="lblTotalCount">0</span>件あります。そのうち<span id="lblPageCount">0</span>件を表示しています。
		<input type="button" id="btnNew" name="btnNew" value="アプリ新規登録" /></p>
		<div id="divList" style="margin-bottom:12px;"></div>
		<form method="post" id="frmBack">
			<input type="hidden" id="pageIndex" name="pageIndex" value="{%$pageIndex%}" />
			<input type="hidden" id="hidSrhName" name="hidSrhName" value="{%$hidSrhName%}" />
			<input type="hidden" id="hidSrhOwner" name="hidSrhOwner" value="{%$hidSrhOwner%}" />
			<input type="hidden" id="hidSrhCate" name="hidSrhCate" value="{%$hidSrhCate%}" />
		</form>
		<script src="{%$staticUrl%}/admin/js/manage/listsite.js?{%$version.js%}"></script>
		
	</div><!--/#container-->

{%include file="footer.phtml"%}