<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" lang="ja" id="fens_admin">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Cache-Control" content="no-cache" />
	<meta http-equiv="imagetoolbar" content="no" />
	<meta http-equiv="Content-Style-Type" content="text/css" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<!--[if lt IE 7]><![endif]-->

    <script type="text/javascript" src="{%$staticUrl%}/cmn/js/jquery.min.js?{%$version.js%}"></script>
<script type="text/javascript" src="{%$staticUrl%}/cmn/js/jquery-ui-1.7.2.custom.min.js?{%$version.js%}"></script>
    <script type="text/javascript" src="{%$staticUrl%}/cmn/js/jquery.string.1.0-min.js?{%$version.js%}"></script>
    <script type="text/javascript" src="{%$staticUrl%}/cmn/js/common.js?{%$version.js%}"></script>
    <script type="text/javascript" src="{%$staticUrl%}/admin/js/manage/main.js?{%$version.js%}"></script>
    <script type="text/javascript" src="{%$staticUrl%}/cmn/js/jquery.form.js?{%$version.js%}"></script>
    <script type="text/javascript" src="{%$staticUrl%}/cmn/js/jquery.validate.js?{%$version.js%}"></script>

	<script type="text/javascript" language="javascript">
		var UrlConfig =  {
		    BaseUrl : '{%$baseUrl%}',
		    StaticUrl : '{%$staticUrl%}'
		};
	</script>
	<link rel="stylesheet" href="{%$staticUrl%}/admin/css/admin.css?{%$version.css%}" type="text/css" media="all" />
	<link rel="stylesheet" href="{%$staticUrl%}/admin/css/main.css?{%$version.css%}" type="text/css" media="all" />
	<link rel="stylesheet" href="{%$staticUrl%}/admin/css/import.css?{%$version.css%}" type="text/css" media="all" />
	<link rel="stylesheet" type="text/css" media="all" href="{%$staticUrl%}/cmn/css/ui-lightness/jquery-ui-1.7.1.custom.css?{%$version.css%}" />
	<title>{%$title%}</title>
</head>



